spring:
    application:
      name: mstransacoes
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:apibanco}
      username: ${DB_USER:postgres}
      password: ${DB_PASSWORD:postgres}
        
    flyway:
      enabled: true
      baseline-on-migrate: false
      locations: classpath:db/migration
      # Força o Flyway a rodar antes de qualquer coisa
      validate-on-migrate: true

    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
          ddl-auto: validate # Valida o schema do banco com as entidades, mas não faz alterações
      show-sql: true
      defer-datasource-initialization: false # Força o Hibernate a esperar o Flyway concluir
      properties:
          jakarta.persistence.schema-generation.database.action: none

server:
  port: 0

eureka:
  client:
    service-url:
      fetch-registry: true
      register-with-eureka: true
      defaultZone: http://localhost:8761/eureka/
#   instance:
#     instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}