spring:
  application:
    name: msextratoconsumer

  # CONFIGURAÇÃO DO KAFKA CONSUMIDOR
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      # ID do grupo de consumidores. Se subirmos 2 instâncias desse app, 
      # o Kafka dividirá as 3 partições entre elas automaticamente por causa deste ID comum.
      group-id: cassandra-extrato-group
      
      # Caso o serviço mude de servidor ou perca o ponto de leitura (offset), 
      # ele começará a ler o tópico desde a primeira mensagem disponível.
      auto-offset-reset: earliest
      
      # CORREÇÃO: Envolvemos o JsonDeserializer dentro de um ErrorHandlingDeserializer.
      # Isso atende ao aviso do log e evita que mensagens corrompidas travem sua aplicação.
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      
      properties:
        # Aponta qual é o deserializador real de fallback que vai tratar o JSON
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        
        # O PULO DO GATO: Força o consumidor a usar o DTO local deste projeto, 
        # ignorando completamente o pacote enviado pelo produtor.
        spring.json.value.default.type: "br.com.apibanco.msextratoconsumer.dtos.TransactionEventDTO"
        
        # CORREÇÃO CRUCIAL: Diz ao Spring para ignorar os cabeçalhos de tipo que vierem na mensagem
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"

  # CONFIGURAÇÃO DO CASSANDRA [1]
  cassandra:
    keyspace-name: bank_history
    # 'cassandra' é o nome do serviço no docker-compose. Se rodar na IDE, usa localhost.
    contact-points: ${CASSANDRA_HOST:localhost}:9042
    local-datacenter: datacenter1
    schema-action: create_if_not_exists # O Spring valida e ajuda a garantir a tabela [1]

server:
  port: 0 # Porta aleatória para não conflitar com outros microserviços

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${random.value}

app:
  spring:
    kafka:
      topic:
        transactions: bank-transactions
      consumer:
        group-id: cassandra-extrato-group
