CREATE TABLE contas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cliente_id BIGINT NOT NULL,
    numero VARCHAR(20) NOT NULL,
    data_abertura TIMESTAMP NOT NULL,
    data_fechamento TIMESTAMP,
    tipo VARCHAR(15) NOT NULL,
    saldo DECIMAL(15, 2) NOT NULL, -- Precisão financeira exata mapeada do BigDecimal
    
    CONSTRAINT pk_conta PRIMARY KEY (id),
    CONSTRAINT uk_conta_numero UNIQUE (numero),
    CONSTRAINT fk_conta_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id)
);
